import '../main.dart';
import 'package:flutter/material.dart';

/// Simple key-based translation helper.
/// Language is read from [AccountBookAppState.language].
class S {
  static final Map<String, String> _zh = {
    'settings': '设置',
    'about': '关于',
    'data_management': '数据管理',
    'export_csv': '导出 CSV',
    'export_csv_hint': '导出全部账单到 CSV 文件',
    'exporting': '导出中…',
    'export_success': '已导出到',
    'export_failed': '导出失败',
    'export_select_range': '选择导出范围',
    'export_all': '导出全部',
    'export_range': '导出范围',
    'today': '今天',
    'this_month': '本月',
    'this_year': '今年',
    'start_date': '开始日期',
    'end_date': '结束日期',
    'clear_data': '清空数据',
    'clear_data_hint': '删除所有账单记录，不可恢复',
    'clear_confirm_title': '确认清空',
    'clear_confirm_body': '确定要删除所有账单记录吗？\n此操作不可恢复！',
    'cancel': '取消',
    'ok': '确定',
    'clear': '清空',
    'cleared': '已清空所有数据',
    'theme_appearance': '主题与外观',
    'dark_mode': '深色模式',
    'dark': '深色',
    'light': '浅色',
    'theme_color': '主题色',
    'pick_theme_color': '选择主题色',
    'preferences': '基础偏好',
    'date_format': '日期格式',
    'currency_unit': '货币单位',
    'language': '语言',
    'version': 'v1.0.1',
    'developer': '开发者',
    'feedback_email': '反馈邮箱',
    'tech_stack': '技术栈',
    'app_slogan': '轻记账 — 让每一笔收支都有迹可循',
    'home_title': '轻记账',
    'income': '收入',
    'expense': '支出',
    'balance': '结余',
    'total': '合计',
    'record': '记录',
    'search': '搜索',
    'add_record': '添加记录',
    'edit_record': '编辑记录',
    'save_changes': '保存修改',
    'amount': '金额',
    'category': '分类',
    'date': '日期',
    'time': '时间',
    'note': '备注',
    'note_optional': '备注（选填）',
    'save': '保存',
    'delete': '删除',
    'confirm_delete': '确认删除',
    'confirm_delete_body': '确定要删除这条记录吗？',
    'no_records': '暂无记录',
    'no_records_this_month': '本月还没有记录',
    'tap_add_hint': '点右下角 + 记一笔吧',
    'no_chart_data': '暂无图表数据',
    'add_more_chart_hint': '多记几笔再来看看吧',
    'monthly_comparison': '月度收支对比',
    'monthly_chart': '月度趋势',
    'category_breakdown': '分类明细',
    'no_expense_records': '暂无支出记录',
    'no_income_records': '暂无收入记录',
    'more_categories': '还有 %d 个分类…',
    'rename_book': '重命名账本',
    'book_name_hint': '输入账本名称',
    'add_record_title': '添加记录',
    'edit_record_title': '编辑记录',
    'amount_required': '请输入金额',
    'amount_invalid': '请输入有效金额',
    'search_hint': '搜索类别、备注、金额…',
    'search_empty_title': '输入关键词搜索账单',
    'search_empty_hint': '支持类别、备注、金额',
    'search_no_results': '没有找到匹配的记录',
    'good_morning': '早上好',
    'good_afternoon': '下午好',
    'good_evening': '晚上好',
    'good_night': '夜深了',
    'calendar_view': '日历视图',
    'chart_view': '图表视图',
    'list_view': '列表视图',
    'confirm': '确定',
    'time_travel_hint': '你也想拥有预知未来的能力？先穿越回来再记账吧',
    'year_month': '%y年%m月',
    'mon': '一',
    'tue': '二',
    'wed': '三',
    'thu': '四',
    'fri': '五',
    'sat': '六',
    'sun': '日',
    'calendar_date': '%m月%d日',
    'calendar_week': '周%s',
    'recorded': '已记一笔 ✓',
    'saved_success': '入账成功 ✓',
  };

  static final Map<String, String> _en = {
    'settings': 'Settings',
    'about': 'About',
    'data_management': 'Data Management',
    'export_csv': 'Export CSV',
    'export_csv_hint': 'Export all records to CSV file',
    'exporting': 'Exporting…',
    'export_success': 'Saved to',
    'export_failed': 'Export failed',
    'export_select_range': 'Select Date Range',
    'export_all': 'Export All',
    'export_range': 'Export Range',
    'today': 'Today',
    'this_month': 'This Month',
    'this_year': 'This Year',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'clear_data': 'Clear All Data',
    'clear_data_hint': 'Delete all records, cannot be undone',
    'clear_confirm_title': 'Confirm Clear',
    'clear_confirm_body': 'Delete all records?\nThis cannot be undone!',
    'cancel': 'Cancel',
    'ok': 'OK',
    'clear': 'Clear',
    'cleared': 'All data cleared',
    'theme_appearance': 'Theme & Appearance',
    'dark_mode': 'Dark Mode',
    'dark': 'Dark',
    'light': 'Light',
    'theme_color': 'Theme Color',
    'pick_theme_color': 'Pick a theme color',
    'preferences': 'Preferences',
    'date_format': 'Date Format',
    'currency_unit': 'Currency',
    'language': 'Language',
    'version': 'v1.0.1',
    'developer': 'Developer',
    'feedback_email': 'Feedback',
    'tech_stack': 'Tech Stack',
    'app_slogan': 'Keep every penny in check.',
    'home_title': 'Account Book',
    'income': 'Income',
    'expense': 'Expense',
    'balance': 'Balance',
    'total': 'Total',
    'record': 'Record',
    'search': 'Search',
    'add_record': 'Add Record',
    'edit_record': 'Edit Record',
    'save_changes': 'Save Changes',
    'amount': 'Amount',
    'category': 'Category',
    'date': 'Date',
    'time': 'Time',
    'note': 'Note',
    'note_optional': 'Note (optional)',
    'save': 'Save',
    'delete': 'Delete',
    'confirm_delete': 'Confirm Delete',
    'confirm_delete_body': 'Delete this record?',
    'no_records': 'No records',
    'no_records_this_month': 'No records this month',
    'tap_add_hint': 'Tap + to add one',
    'no_chart_data': 'No chart data',
    'add_more_chart_hint': 'Add more records to see charts',
    'monthly_comparison': 'Monthly Comparison',
    'monthly_chart': 'Monthly Trend',
    'category_breakdown': 'By Category',
    'no_expense_records': 'No expenses',
    'no_income_records': 'No income',
    'more_categories': '%d more…',
    'rename_book': 'Rename Book',
    'book_name_hint': 'Enter book name',
    'add_record_title': 'Add Record',
    'edit_record_title': 'Edit Record',
    'amount_required': 'Enter an amount',
    'amount_invalid': 'Enter a valid amount',
    'search_hint': 'Search category, note, amount…',
    'search_empty_title': 'Search your bills',
    'search_empty_hint': 'By category, note, or amount',
    'search_no_results': 'No matching records',
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'good_night': 'Late night',
    'calendar_view': 'Calendar',
    'chart_view': 'Chart',
    'list_view': 'List',
    'confirm': 'Confirm',
    'time_travel_hint': 'Can\'t predict the future — pick a valid date!',
    'year_month': '%y/%m',
    'mon': 'Mon',
    'tue': 'Tue',
    'wed': 'Wed',
    'thu': 'Thu',
    'fri': 'Fri',
    'sat': 'Sat',
    'sun': 'Sun',
    'calendar_date': '%m/%d',
    'calendar_week': '%s',
    'recorded': 'Recorded ✓',
    'saved_success': 'Saved ✓',
  };

  /// Get translated string for the current app language.
  static String t(BuildContext context, String key) {
    final lang = AccountBookApp.of(context)?.language ?? 'zh';
    return _get(lang, key);
  }

  /// Get translated string for a given language code.
  static String tl(String lang, String key) {
    return _get(lang, key);
  }

  static String _get(String lang, String key) {
    final map = lang == 'en' ? _en : _zh;
    return map[key] ?? _zh[key] ?? key;
  }
}
